version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  yiipgsql:
    image: postgres:10-alpine
    volumes:
      - type: volume
        source: ci_pgsql_data
        target: /var/lib/pgsql/data
    environment:
      - "POSTGRES_USER=currencyinfo"
      - "POSTGRES_PASSWORD=currencyinfo"
      - "PGDATA=/var/lib/pgsql/data"
      - "POSTGRES_DB=cipgsql"
    ports:
      - "5456:5432"
  yiipgsql-test:
    image: postgres:10-alpine
    volumes:
      - type: volume
        source: ci_pgsql_test_data
        target: /var/lib/pgsql/data
    environment:
      - "POSTGRES_USER=currencyinfo_test"
      - "POSTGRES_PASSWORD=currencyinfo_test"
      - "PGDATA=/var/lib/pgsql/data"
      - "POSTGRES_DB=cipgsql"
    ports:
      - "5466:5432"

volumes:
  ci_pgsql_data:
  ci_pgsql_test_data: