version: '2'
networks:
  appnet:
    external:
      name: appnet
services:
  php:
    networks:
      - appnet
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
  yiipgsql:
    networks:
      - appnet
    image: postgres:10-alpine
    volumes:
      - type: volume
        source: yii_data
        target: /var/lib/pgsql/data
    environment:
      - "POSTGRES_USER=yii"
      - "POSTGRES_PASSWORD=yii"
      - "PGDATA=/var/lib/pgsql/data"
      - "POSTGRES_DB=yii_db"
    ports:
      - "5456:5432"
  yiipgsql-test:
    networks:
      - appnet
    image: postgres:10-alpine
    volumes:
      - type: volume
        source: yii_test_data
        target: /var/lib/pgsql/data
    environment:
      - "POSTGRES_USER=yii_test"
      - "POSTGRES_PASSWORD=yii_test"
      - "PGDATA=/var/lib/pgsql/data"
      - "POSTGRES_DB=yii_test_db"
    ports:
      - "5466:5432"
volumes:
  yii_data:
  yii_test_data: